# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.deconvolveJump <- function(grid, observations, time, leftValue, rightValue, typeFilter, inputFilter, covariances) {
    .Call(`_clampSeg_deconvolveJump`, grid, observations, time, leftValue, rightValue, typeFilter, inputFilter, covariances)
}

.deconvolvePeak <- function(gridLeft, gridRight, observations, time, leftValue, rightValue, typeFilter, inputFilter, covariances, tolerance) {
    .Call(`_clampSeg_deconvolvePeak`, gridLeft, gridRight, observations, time, leftValue, rightValue, typeFilter, inputFilter, covariances, tolerance)
}

